---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "leah-filkin-app"
  annotations:
    description: "leah-filkin-app release template"
objects:

  - kind: Deployment #declaration of pods
    apiVersion: apps/v1
    metadata:
      name: $(deploymentName)
      namespace: $(namespace)
      labels:
        app: $(name)
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: $(name)
      template:
        metadata:
          labels:
            app: $(name)
        spec:
          containers:
            - image: $(imageName):$(imageTag)
              name: $(name)
              ports:
                - containerPort: $(containerPort)

  - kind: Service #making it so that the containers can communicate
    apiVersion: v1
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      name: $(serviceName)
      namespace: $(namespace)
      labels:
        app: $(name)
    spec:
      ports:
        - port: $(containerPort)
          targetPort: $(containerPort)
      selector:
        app: $(name)

  - kind: Ingress #getting it on the web
    apiVersion: networking.k8s.io/v1
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: $(ingressName)
      namespace: $(namespace)
      labels:
        app: $(name)
    spec:
      rules:
        - host: $(host)
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: $(serviceName)
                    port:
                      number: $(containerPort)
      tls:
        - hosts:
            - $(host)
          secretName: "leah-filkin-tls"