---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "leah-app-deployment"
  annotations:
    description: "Leah release template"
objects:

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: $(deploymentName)
      namespace: $(namespace)
      labels:
        app: $(name)
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: $(name)
      template:
        metadata:
          labels:
            app: $(name)
        spec:
          containers:
            - name: $(name)
              image: $(image):$(imageTag)
              ports:
                - containerPort: $((containerPort))

  - kind: Ingress
    apiVersion: networking.k8s.io/v1
    metadata:
      name: $(ingressName)
      namespace: $(namespace)
      labels:
        app: $(name)
      annotations:
        kubernetes.io/tls-acme: "true"
    spec:
      tls:
        - hosts:
            - $(host)
          secretName: $(name)-tls
      rules:
        - host: $(host)
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: $(serviceName)
                    port:
                      number: 80

  - kind: Service
    apiVersion: v1
    metadata:
      name: $(serviceName)
      namespace: $(namespace)
      labels:
        app: $(name)
      annotations:
        prometheus.io/scrape: "true"
    spec:
      ports:
        - port: 80
          targetPort: $((containerPort))
      selector:
        app: $(name)
